apiVersion: v1
kind: Pod
metadata:
  name: example-conflict-with-limitrange-cpu
  namespace: nshelm
spec:
  containers:
  - name: demo
    image: nginx:1.25
    resources:
      requests:
        cpu: 700m
